New betteradd plant
Som-Energia/plantmonitor pull request #25
Opened 2022-04-14 12:44 UTC by polmonso

Pack de canvis per a gestionar les incidències:

https://secure.helpscout.net/conversation/1845708994/11925770?folderId=6598363
https://secure.helpscout.net/conversation/1800815226/11329808?folderId=6598391

2022-04-19 08:25 UTC, catbru approved these changes

2022-04-21 10:53 UTC, AlbertoRasillo requested changes
Bajo mi punto de vista vendría bien separar las clases del modelo en diferentes ficheros. ¿Cómo lo ves? Pienso que vendría bien a la hora entender el código que estén agrupadas las clases y sus funciones. Lo podemos plantear como millora de bugbuster.

He visto que algunas funciones se testean desde test_model.py y otras en test_addPlant.py. Algunas no me queda claro si testean todos los parámetros exportados/importados test_importExportPlant__with_details.  Es posible que se puedan repetir test en ambos ficheros. ¿Cómo podemos diferenciar que test van en uno u otro fichero? me cuesta un poco diferenciarlo. También lo incluiria como millora de bugbuster junto con el anterior punto.

2022-04-21 10:53 UTC, AlbertoRasillo commented on test_addPlant.py
> +    def test_importExportPlant__new_plant(self):
test __ normalize

2022-04-21 10:53 UTC, AlbertoRasillo commented on test_addPlant.py
> +    def test_importExportPlant__without_description(self):
test __ normalize

2022-04-21 10:53 UTC, AlbertoRasillo commented on test_addPlant.py
> +    def test_importExportPlant__with_details(self):
test __ normalize

2022-04-21 10:53 UTC, AlbertoRasillo commented on conf/settings/testing.py
> +# MONSOL_CREDENTIALS = test_env.json('MONSOL_CREDENTIALS')
comentario en configuración necesario?

2022-04-21 10:53 UTC, AlbertoRasillo commented on conf/settings/testing.py
> +# MONSOL = test_env.json('MONSOL')
comentario en configuración necesario?

2022-04-21 10:53 UTC, AlbertoRasillo commented on conf/settings/devel.py
> +# MONSOL = devel_env.json('MONSOL')
comentario en configuración necesario?

2022-04-21 10:53 UTC, AlbertoRasillo commented on conf/settings/devel.py
> +# MONSOL_CREDENTIALS = devel_env.json('MONSOL_CREDENTIALS')
comentario en configuración necesario?

2022-04-21 10:53 UTC, AlbertoRasillo commented on test_addPlant.py
> +        #orm.set_sql_debug(debug=True, show_values=True)
comentario necesario?

2022-04-21 10:53 UTC, AlbertoRasillo commented on ORM/models.py
> +                devs = [SensorTemperatureModule.get(plant=self, name=sensor['temperatureModuleSensor'].name) or SensorTemperatureModule(plant=self, name=sensor['temperatureModuleSensor'].name) for se
recomendable evitar lineas tan largas

2022-04-21 10:53 UTC, AlbertoRasillo commented on ORM/models.py
> +                devs = [SensorIrradiation.get(plant=self, name=sensor['irradiationSensor'].name) or SensorIrradiation(plant=self, name=sensor['irradiationSensor'].name) for sensor in plant.irradiatio
recomendable evitar lineas tan largas

2022-04-21 10:53 UTC, AlbertoRasillo commented on ORM/models.py
> +                devs = [SensorTemperatureAmbient.get(plant=self, name=sensor['temperatureAmbientSensor'].name) or SensorTemperatureAmbient(plant=self, name=sensor['temperatureAmbientSensor'].name) fo
recomendable evitar lineas tan largas

2022-04-21 10:53 UTC, AlbertoRasillo commented on ORM/models.py
> +import pytz
Es posible poner primero todos los imports y después todos los from

2022-04-21 10:53 UTC, AlbertoRasillo commented on ORM/models.py
> +                devs = [Meter.get(plant=self, name=meter['meter'].name) or Meter(plant=self, name=meter['meter'].name) for meter in plant.meters]
devs = device? en algunos sitios se indica device y en otros devs

2022-04-21 10:53 UTC, AlbertoRasillo commented on test_addPlant.py
> +                    plantParameters:
se testea testean los plantParameters, no me queda claro lo que testea este test. ¿Si así no faltan más parámetros por incluir?

2022-04-21 10:53 UTC, AlbertoRasillo commented on ORM/models.py
> +                'peakPowerMWp': int(self.peak_power_w/1000000),
Tengo la duda de si las conversiones en unidades en la misma linea es la mejor forma. Seguramente si. Podemos valorar usar funciones de conversión

2022-04-22 06:55 UTC, polmonso commented on ORM/models.py
> +                'peakPowerMWp': int(self.peak_power_w/1000000),
Aquesta si que la deixaré així. El format d'entrada ve marcat pel què tenen posat a l'excel de dades fixes o l'excel d'unificació de noms. Si que hi posaré decimals però, que no té perquè ser un int de fet.

2022-04-22 06:56 UTC, polmonso commented on addPlant.py
> +    # orm.set_sql_debug(debug=True, show_values=True)
És útil tenir-ho per si cal debuggar pony, que sinó no pensem que podem tenir log de totes les transaccions

2022-04-22 06:57 UTC, polmonso commented on conf/settings/devel.py
> +# MONSOL = devel_env.json('MONSOL')
Això està aquí per si mai ens tornen a demanar de connectar-nos a Monsol. Vam veure que de moment no ens servia perquè no tenien inversors, però pot ser que ressorgeixi.

2022-04-22 07:03 UTC, polmonso commented on test_addPlant.py
> +                    plantParameters:
si, es testegen els camps obligatoris i prou de plantparameters i el PlantLocation

2022-04-22 07:12 UTC, polmonso commented on ORM/models.py
> +import pytz
El que es salta la norma és l'snippet de logging que hauríem d'externalitzar i posar en un fitxer a part per a què no pol·lucioni el codi amb 5 línies. Ho deixo així de moment pendent de treure per from log import logger

2022-04-25 16:47 UTC, closed without merging